apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sumanthhoskote/python-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret   # <-- use the secret you already created
